(() => {
  'use strict';

  const KEY = 'ham-safar-state-v1';
  const today = () => new Date().toISOString().slice(0, 10);
  const fa = new Intl.NumberFormat('fa-IR');
  const money = n => `${fa.format(Math.round(Number(n) || 0))} تومان`;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const id = () => `${Date.now()}-${Math.random().toString(16).slice(2)}`;

  const categories = {
    'خودرو': ['بنزین','پارکینگ','عوارض','کارواش','تعمیر','روغن و سرویس','سایر'],
    'خورد و خوراک': ['رستوران','فست‌فود','نوشیدنی','تنقلات','کافه'],
    'اقامت': ['هتل','ویلا','اقامتگاه','سایر'],
    'خرید': ['لباس','سوغاتی','لوازم','سایر'],
    'تفریح': ['بلیت','موزه','پارک','تفریح','سایر'],
    'سایر': ['سایر']
  };
  const defaults = () => ({
    trip: {}, people: [], expenses: [], pool: { contributions: [], expenses: [] }, budget: 0,
    itinerary: [], checklist: [], reservations: [], documents: [], settings: {
      theme:'dark', animation:true, voiceLang:'fa-IR', autoRead:false, provider:'local', model:'local-context-model', endpoint:'', apiKey:''
    }, firstRun: true
  });
  let state = load();
  let currentScreen = 'travel';
  let recognition = null;
  let listening = false;
  let toastTimer;

  function load() { try { return Object.assign(defaults(), JSON.parse(localStorage.getItem(KEY) || '{}')); } catch { return defaults(); } }
  function persist() { const safe = JSON.parse(JSON.stringify(state)); safe.settings.apiKey = ''; localStorage.setItem(KEY, JSON.stringify(safe)); }
  function commit() { persist(); render(); }
  function $(s) { return document.querySelector(s); }
  function $$(s) { return [...document.querySelectorAll(s)]; }
  function toast(message) { const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('show'),2600); }
  function openModal(name) { const el=$(`#${name}`); if(el) el.classList.add('active'); }
  function closeModal(name) { const el=$(`#${name}`); if(el) el.classList.remove('active'); }
  function selectedPeople() { return state.people.map(p=>p.name); }
  function totalSpent() { return state.expenses.reduce((s,e)=>s+Number(e.baseAmount || e.amount || 0),0); }
  function baseAmount(e) { return Number(e.baseAmount || e.amount || 0); }
  function todaySpent() { return state.expenses.filter(e=>e.date===today()).reduce((s,e)=>s+baseAmount(e),0); }
  function categoryTotals() { return state.expenses.reduce((o,e)=>(o[e.category]=(o[e.category]||0)+baseAmount(e),o),{}); }
  function payerTotals() { return state.people.reduce((o,p)=>(o[p.name]=state.expenses.filter(e=>e.payer===p.name).reduce((s,e)=>s+baseAmount(e),0),o),{}); }
  function shares(e) {
    const names=e.beneficiaries?.length ? e.beneficiaries : selectedPeople();
    if(!names.length) return {};
    const total=baseAmount(e), out={};
    if(e.splitMode==='amount') names.forEach(n=>out[n]=Number(e.splitValues?.[n]||0));
    else if(e.splitMode==='percent') names.forEach(n=>out[n]=total*Number(e.splitValues?.[n]||0)/100);
    else if(e.splitMode==='shares') { const sum=names.reduce((s,n)=>s+Number(e.splitValues?.[n]||0),0)||1; names.forEach(n=>out[n]=total*Number(e.splitValues?.[n]||0)/sum); }
    else names.forEach(n=>out[n]=total/names.length);
    return out;
  }
  function balances() {
    const paid=payerTotals(), owed={}; state.people.forEach(p=>owed[p.name]=0);
    state.expenses.forEach(e=>Object.entries(shares(e)).forEach(([n,v])=>owed[n]=(owed[n]||0)+v));
    return state.people.map(p=>({name:p.name, paid:paid[p.name]||0, owed:owed[p.name]||0, net:(paid[p.name]||0)-(owed[p.name]||0)}));
  }
  function settlements() {
    const creditors=balances().filter(x=>x.net>0.5).map(x=>({...x}));
    const debtors=balances().filter(x=>x.net<-0.5).map(x=>({...x,net:-x.net})); const result=[];
    debtors.forEach(d=>creditors.forEach(c=>{ if(d.net<=.5||c.net<=.5)return; const amount=Math.min(d.net,c.net); result.push({from:d.name,to:c.name,amount}); d.net-=amount;c.net-=amount; }));
    return result;
  }
  function formatDate(v) { return v ? new Date(`${v}T00:00:00`).toLocaleDateString('fa-IR') : '—'; }
  function render() {
    document.body.dataset.theme=state.settings.theme; document.body.dataset.reducedMotion=state.settings.animation?'false':'true';
    const trip=state.trip||{}; $('#tripName').textContent=trip.name||'سفر'; $('#tripDestination').textContent=trip.destination||'مقصد'; $('#tripDuration').textContent=`${fa.format(trip.duration||0)} روز`; $('#headerTitle').textContent=trip.name||'هم‌سفر';
    const total=totalSpent(), budget=Number(state.budget||0), remaining=budget-total, pct=budget?Math.min(100,total/budget*100):0;
    $('#totalSpentCard').textContent=money(total); $('#todaySpentCard').textContent=money(todaySpent()); $('#perPersonCard').textContent=money(state.people.length?total/state.people.length:0); $('#budgetRemainingCard').textContent=money(remaining);
    $('#budgetFill').style.width=`${pct}%`; $('#budgetUsageText').textContent=`${fa.format(Math.round(pct))}٪ مصرف شده`; $('#budgetStatusText').textContent=budget&&total>budget?'بودجه سفر رد شده':pct>=80?'نزدیک سقف بودجه':'در محدوده';
    renderCharts(); renderRecent(); renderPeople(); renderExpenses(); renderReports(); renderSettlement(); renderSelectors(); renderSuggestion(); renderAIWelcome();
  }
  function renderCharts() {
    const ct=categoryTotals(), max=Math.max(1,...Object.values(ct)); $('#categoryChart').innerHTML=Object.entries(ct).length?Object.entries(ct).map(([k,v])=>`<div class="bar-row"><span class="bar-label">${esc(k)}</span><span class="bar-track"><span class="bar-fill" style="width:${v/max*100}%"></span></span><small>${money(v)}</small></div>`).join(''):'<p>هنوز هزینه‌ای ثبت نشده</p>';
    const pt=payerTotals(), mx=Math.max(1,...Object.values(pt)); $('#personChart').innerHTML=Object.entries(pt).length?Object.entries(pt).map(([k,v])=>`<div class="vertical-bar-wrap"><span class="vertical-bar" style="height:${Math.max(32,v/mx*140)}px"></span><span class="vertical-bar-label">${esc(k)}</span></div>`).join(''):'<p>هنوز فردی اضافه نشده</p>';
  }
  function expenseHtml(e) { return `<div class="list-item"><div class="meta"><strong>${esc(e.note||e.subcategory||e.category)}</strong><small>${esc(e.payer)} · ${esc(e.category)} / ${esc(e.subcategory||'سایر')} · ${formatDate(e.date)}</small></div><div class="item-actions"><span class="value">${money(baseAmount(e))}</span><button data-edit-expense="${e.id}" aria-label="ویرایش">✎</button><button data-delete-expense="${e.id}" aria-label="حذف">🗑</button></div></div>`; }
  function renderRecent() { $('#recentExpenses').innerHTML=state.expenses.slice(-4).reverse().map(expenseHtml).join('')||'<p>هنوز هزینه‌ای ثبت نشده</p>'; }
  function renderPeople() { $('#peopleList').innerHTML=state.people.length?balances().map(p=>`<div class="list-item"><div class="meta"><strong>${esc(p.name)}</strong><small>پرداخت: ${money(p.paid)} · سهم: ${money(p.owed)}</small></div><div class="item-actions"><span class="value" style="color:${p.net>=0?'var(--success)':'var(--danger)'}">${p.net>=0?'طلب':'بدهی'} ${money(Math.abs(p.net))}</span><button data-delete-person="${esc(p.name)}">🗑</button></div></div>`).join(''):'<p>اول افراد سفر را اضافه کن</p>'; $('#peopleModalList').innerHTML=state.people.map(p=>`<div class="mini-person"><span>${esc(p.name)}</span><button data-delete-person="${esc(p.name)}">🗑</button></div>`).join(''); }
  function renderExpenses() { const q=($('#expenseSearch')?.value||'').trim().toLowerCase(), person=$('#expenseFilterPerson')?.value||''; const list=state.expenses.filter(e=>(!q||JSON.stringify(e).toLowerCase().includes(q))&&(!person||e.payer===person)); $('#expenseList').innerHTML=list.length?list.slice().reverse().map(expenseHtml).join(''):'<p>هزینه‌ای مطابق جستجو پیدا نشد</p>'; }
  function renderSettlement() { const s=settlements(); $('#settlementSummary').innerHTML=s.length?s.map(x=>`<div class="list-item"><span>${esc(x.from)} ← ${esc(x.to)}</span><strong>${money(x.amount)}</strong></div>`).join(''):'<p>تسویه‌ای باقی نمانده است.</p>'; $('#balanceSummary').innerHTML=balances().map(x=>`<div class="list-item"><span>${esc(x.name)}</span><strong>${x.net>=0?'طلب':'بدهی'} ${money(Math.abs(x.net))}</strong></div>`).join('')||'<p>اطلاعاتی برای نمایش نیست.</p>'; }
  function renderReports() { const total=totalSpent(), days=new Set(state.expenses.map(e=>e.date)).size; const daysMap={}; state.expenses.forEach(e=>daysMap[e.date]=(daysMap[e.date]||0)+baseAmount(e)); const topDay=Object.entries(daysMap).sort((a,b)=>b[1]-a[1])[0], topCat=Object.entries(categoryTotals()).sort((a,b)=>b[1]-a[1])[0]; $('#reportTransactionCount').textContent=fa.format(state.expenses.length); $('#reportDailyAvg').textContent=money(days?total/days:0); $('#reportMostExpensiveDay').textContent=topDay?formatDate(topDay[0]):'—'; $('#reportMostExpensiveCategory').textContent=topCat?topCat[0]:'—'; $('#reportSummary').innerHTML=`<div class="line"><span>کل هزینه</span><strong>${money(total)}</strong></div><div class="line"><span>هزینه هر نفر</span><strong>${money(state.people.length?total/state.people.length:0)}</strong></div><div class="line"><span>تعداد افراد</span><strong>${fa.format(state.people.length)}</strong></div>`; }
  function renderSuggestion() { const total=totalSpent(), b=Number(state.budget||0); $('#aiSuggestion').textContent=!state.people.length?'برای شروع، افراد سفر را اضافه کن.':!state.expenses.length?'هنوز هزینه‌ای ثبت نشده؛ می‌توانی با Voice شروع کنی.':b&&total/b>=.8?'مصرف بودجه به سقف نزدیک شده؛ قبل از هزینه بعدی بررسی کن.':'وضعیت هزینه‌ها ثبت شد؛ می‌توانی از هم‌یار سفر درباره تسویه بپرسی.'; }
  function renderSelectors() { const opts=state.people.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join(''); ['expensePayer','expenseFilterPerson'].forEach(s=>{const el=$(`#${s}`);if(!el)return;const old=el.value;el.innerHTML=(s==='expenseFilterPerson'?'<option value="">همه افراد</option>':'')+opts;el.value=old;}); const ben=$('#expenseBeneficiaries'); if(ben) ben.innerHTML=opts; const cat=$('#expenseCategory'); if(cat){const old=cat.value;cat.innerHTML=Object.keys(categories).map(x=>`<option>${x}</option>`).join('');cat.value=old||Object.keys(categories)[0];updateSubcategories();} }
  function updateSubcategories(){const c=$('#expenseCategory')?.value, el=$('#expenseSubCategory');if(!el)return;el.innerHTML=(categories[c]||['سایر']).map(x=>`<option>${x}</option>`).join('');}
  function renderAIWelcome(){const box=$('#aiMessages');if(box&&!box.children.length)addMessage('ai','سلام! من هم‌یار محلی سفرم. می‌توانم هزینه‌ها، بودجه و تسویه را از داده‌های همین اپ تحلیل کنم.');}
  function addMessage(who,text){const box=$('#aiMessages');const el=document.createElement('div');el.className=`message ${who}`;el.textContent=text;box.appendChild(el);box.scrollTop=box.scrollHeight;}
  function localAI(q){const s=q.toLowerCase();if(/چقدر|کل.*خرج|هزینه.*تا/.test(s))return `تا الان ${money(totalSpent())} خرج کرده‌اید.`; const person=state.people.find(p=>s.includes(p.name.toLowerCase())); if(person&&/پرداخت|خرج|هزینه/.test(s)){const p=payerTotals()[person.name]||0;return `${person.name} تا الان ${money(p)} پرداخت کرده است.`;} if(/بیشترین.*هزینه|گران.*دسته/.test(s)){const x=Object.entries(categoryTotals()).sort((a,b)=>b[1]-a[1])[0];return x?`بیشترین هزینه مربوط به «${x[0]}» با ${money(x[1])} است.`:'هنوز هزینه‌ای ثبت نشده.';} if(/تسویه|بدهی|طلب/.test(s)){const x=settlements();return x.length?x.map(a=>`${a.from} باید ${money(a.amount)} به ${a.to} بدهد`).join('؛ '):'در حال حاضر تسویه‌ای لازم نیست.';} if(/بودجه/.test(s))return `بودجه ${money(state.budget)} است و ${money(Math.max(0,state.budget-totalSpent()))} باقی مانده.`; if(/راهنما|چطور/.test(s))return 'برای ثبت هزینه، از تب هزینه‌ها یا دکمه Voice استفاده کن. اطلاعات در همین دستگاه ذخیره می‌شود.';return 'من در حالت دستیار محلی هستم و می‌توانم درباره هزینه‌ها، بودجه و تسویه همین سفر پاسخ بدهم.';}
  function parseNumber(text){let t=text.replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/٬|,/g,'').replace(/٫/g,'.');const m=t.match(/(\d+(?:\.\d+)?)\s*(میلیون|هزار)?/);if(!m)return null;let n=Number(m[1]);if(m[2]==='میلیون')n*=1000000;if(m[2]==='هزار')n*=1000;return n;}
  function parseVoice(text){const normalized=text.replace(/[يى]/g,'ی');const person=state.people.find(p=>normalized.includes(p.name));const amount=parseNumber(normalized);let category='سایر', subcategory='سایر';for(const [c,subs] of Object.entries(categories)){const hit=subs.find(x=>normalized.includes(x));if(hit){category=c;subcategory=hit;break;}}return person&&amount?{person:person.name,amount,category,subcategory}:null;}
  function startVoice(){if(!('SpeechRecognition'in window||'webkitSpeechRecognition'in window)){toast('تشخیص گفتار در این WebView پشتیبانی نمی‌شود');return;} if(listening)return; const C=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new C();recognition.lang=state.settings.voiceLang||'fa-IR';recognition.interimResults=false;recognition.continuous=false;listening=true;$('#voiceStatusText').textContent='در حال شنیدن...';$('#voiceToggle').classList.add('listening');recognition.onresult=e=>{const text=e.results[0][0].transcript;$('#voiceResultText').textContent=`«${text}»`;const p=parseVoice(text);if(!p){toast('درست متوجه نشدم؛ نام، مبلغ و دسته را واضح بگو.');return;}const eobj={id:id(),payer:p.person,amount:p.amount,baseAmount:p.amount,currency:'IRR',category:p.category,subcategory:p.subcategory,paymentMethod:'person',splitMode:'equal',beneficiaries:selectedPeople(),note:'ثبت با صدا',date:today()};state.expenses.push(eobj);commit();$('#voiceResultText').textContent=`✓ ${p.person} · ✓ ${money(p.amount)} · ✓ ${p.category} / ${p.subcategory}`;toast('هزینه با موفقیت ثبت شد');};recognition.onerror=()=>toast('تشخیص صدا ناموفق بود؛ دوباره تلاش کن');recognition.onend=stopVoice;recognition.start();}
  function stopVoice(){if(recognition){try{recognition.stop();}catch{}}recognition=null;listening=false;$('#voiceStatusText').textContent='آماده';$('#voiceToggle').classList.remove('listening');}
  function createTrip(e){e.preventDefault();const names=$('#peopleInput').value.split(/[،,]/).map(x=>x.trim()).filter(Boolean);state.trip={name:$('#tripNameInput').value.trim(),destination:$('#tripDestinationInput').value.trim(),startDate:$('#tripStartDateInput').value,duration:Number($('#tripDurationInput').value)||1};state.budget=Number($('#tripBudgetInput').value)||0;state.people=[...new Set(names)].map(name=>({id:id(),name}));state.firstRun=false;commit();closeModal('welcomeModal');toast('سفر ساخته شد');}
  function addPerson(e){e.preventDefault();const name=$('#peopleNameInput').value.trim();if(!name)return;if(state.people.some(p=>p.name===name))return toast('این فرد قبلاً اضافه شده است');state.people.push({id:id(),name});$('#peopleNameInput').value='';commit();}
  function openExpense(){if(!state.people.length)return toast('اول افراد سفر را اضافه کن');renderSelectors();$('#expenseDate').value=today();$('#expenseForm').dataset.edit='';$('#expenseSplitMode').value='equal';updateSplitConfig();openModal('expenseModal');}
  function updateSplitConfig(){const mode=$('#expenseSplitMode').value, names=[...document.querySelector('#expenseBeneficiaries').selectedOptions].map(o=>o.value);const chosen=names.length?names:selectedPeople();$('#splitConfigWrap').innerHTML=mode==='equal'?'<small>سهم افراد به‌صورت مساوی محاسبه می‌شود.</small>':chosen.map(n=>`<div class="split-config-item"><span>${esc(n)}</span><input class="base-input split-value" data-person="${esc(n)}" type="number" min="0" placeholder="${mode==='percent'?'درصد':mode==='shares'?'سهم':'مبلغ'}" /></div>`).join('')||'<small>افراد ذی‌نفع را انتخاب کن.</small>';}
  function saveExpense(e){e.preventDefault();const amount=Number($('#expenseAmount').value);const payer=$('#expensePayer').value;if(!payer||!amount)return toast('پرداخت‌کننده و مبلغ را وارد کن');const ben=[...$('#expenseBeneficiaries').selectedOptions].map(o=>o.value);const mode=$('#expenseSplitMode').value, vals={};$$('.split-value').forEach(x=>vals[x.dataset.person]=Number(x.value)||0);const obj={id:$('#expenseForm').dataset.edit||id(),payer,amount,baseAmount:amount,currency:$('#expenseCurrency').value,category:$('#expenseCategory').value,subcategory:$('#expenseSubCategory').value,paymentMethod:$('#expensePaymentMethod').value,splitMode:mode,splitValues:vals,beneficiaries:ben,note:$('#expenseNote').value.trim(),date:$('#expenseDate').value||today()};const i=state.expenses.findIndex(x=>x.id===obj.id);if(i>=0)state.expenses[i]=obj;else state.expenses.push(obj);commit();closeModal('expenseModal');toast(i>=0?'هزینه ویرایش شد':'هزینه ثبت شد');}
  function backup(){const copy=JSON.parse(JSON.stringify(state));copy.settings.apiKey='';const blob=new Blob([JSON.stringify(copy,null,2)],{type:'application/json'});download(blob,`ham-safar-backup-${today()}.json`);}
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function exportCSV(){const rows=[['Date','Person','Amount','Currency','Category','Payment','Beneficiaries','Note'],...state.expenses.map(e=>[e.date,e.payer,baseAmount(e),e.currency,e.category,e.paymentMethod,(e.beneficiaries||[]).join(' | '),e.note])];const csv='\ufeff'+rows.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),'ham-safar-expenses.csv');}
  function switchScreen(screen){currentScreen=screen;$$('.screen').forEach(x=>x.classList.toggle('active',x.id===`${screen}Screen`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.screen===screen));}
  function bind(){ $('#tripCreateForm').addEventListener('submit',createTrip);$('#peopleForm').addEventListener('submit',addPerson);$('#addPersonBtn').onclick=()=>openModal('peopleModal');$('#addExpenseBtn').onclick=openExpense;$('#setBudgetBtn').onclick=()=>{const n=prompt('بودجه کل را به تومان وارد کن',state.budget);if(n!==null){state.budget=Number(n)||0;commit();}};$('#expenseForm').addEventListener('submit',saveExpense);$('#expenseCategory').onchange=updateSubcategories;$('#expenseSplitMode').onchange=updateSplitConfig;$('#expenseBeneficiaries').onchange=updateSplitConfig;$('#expenseSearch').oninput=renderExpenses;$('#expenseFilterPerson').onchange=renderExpenses;$('#showAllExpenses').onclick=()=>{switchTab('expenses');};$('#csvExportBtn').onclick=exportCSV;$('#csvExportBtnSettings').onclick=exportCSV;$('#backupBtn').onclick=backup;$('#resetDataBtn').onclick=()=>{if(confirm('همه اطلاعات سفر حذف شود؟')){localStorage.removeItem(KEY);location.reload();}};$('#restoreInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{if(!confirm('اطلاعات فعلی با پشتیبان جایگزین شود؟'))return;const incoming=JSON.parse(reader.result);state=Object.assign(defaults(),incoming);state.settings.apiKey='';commit();toast('بازیابی انجام شد');}catch{toast('فایل پشتیبان معتبر نیست');}};reader.readAsText(file);};$('#openSettings').onclick=()=>{loadSettingsForm();openModal('settingsModal');};$('#themeSelect').onchange=e=>{state.settings.theme=e.target.value;commit();};$('#animationToggle').onchange=e=>{state.settings.animation=e.target.checked;commit();};$('#aiProviderSelect').onchange=e=>{state.settings.provider=e.target.value;commit();};$('#aiInput').onkeydown=e=>{if(e.key==='Enter')sendAI();};$('#aiSendBtn').onclick=sendAI;$('#aiVoiceBtn').onclick=()=>{switchScreen('voice');startVoice();};$('#voiceToggle').onclick=()=>listening?stopVoice():startVoice();
    $$('.nav-item').forEach(b=>b.onclick=()=>switchScreen(b.dataset.screen));$$('.tab-btn').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$$('.close-modal').forEach(b=>b.onclick=()=>closeModal(b.dataset.target));document.addEventListener('click',handleActions);window.addEventListener('popstate',()=>{});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const open=$('.modal.active');if(open)open.classList.remove('active');else switchScreen('travel');}});
  }
  function switchTab(tab){$$('.tab-btn').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));$$('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===`tab-${tab}`));}
  function handleActions(e){const del=e.target.closest('[data-delete-expense]');if(del){if(confirm('این هزینه حذف شود؟')){state.expenses=state.expenses.filter(x=>x.id!==del.dataset.deleteExpense);commit();}}const edit=e.target.closest('[data-edit-expense]');if(edit){const x=state.expenses.find(a=>a.id===edit.dataset.editExpense);if(!x)return;openExpense();$('#expenseForm').dataset.edit=x.id;Object.entries({expensePayer:x.payer,expenseAmount:x.amount,expenseCurrency:x.currency,expenseCategory:x.category,expenseSubCategory:x.subcategory,expensePaymentMethod:x.paymentMethod,expenseSplitMode:x.splitMode,expenseNote:x.note,expenseDate:x.date}).forEach(([k,v])=>{const el=$(`#${k}`);if(el)el.value=v||''});setTimeout(()=>{[...$('#expenseBeneficiaries').options].forEach(o=>o.selected=(x.beneficiaries||[]).includes(o.value));updateSplitConfig();},0);}const dp=e.target.closest('[data-delete-person]');if(dp){if(confirm('این فرد حذف شود؟')){state.people=state.people.filter(p=>p.name!==dp.dataset.deletePerson);commit();}}}
  function sendAI(){const input=$('#aiInput'),q=input.value.trim();if(!q)return;input.value='';addMessage('user',q);setTimeout(()=>{const answer=localAI(q);addMessage('ai',answer);if(state.settings.autoRead&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(answer));}},300);}
  function loadSettingsForm(){const s=state.settings;$('#themeSelect').value=s.theme;$('#animationToggle').checked=s.animation;$('#voiceLangSelect').value=s.voiceLang;$('#autoReadToggle').checked=s.autoRead;$('#aiProviderSelect').value=s.provider;$('#aiModelInput').value=s.model;$('#aiEndpointInput').value=s.endpoint;$('#aiKeyInput').value='';$('#voiceLangSelect').onchange=e=>{s.voiceLang=e.target.value;commit();};$('#autoReadToggle').onchange=e=>{s.autoRead=e.target.checked;commit();};$('#aiModelInput').onchange=e=>{s.model=e.target.value;commit();};$('#aiEndpointInput').onchange=e=>{s.endpoint=e.target.value;commit();};$('#aiKeyInput').onchange=e=>{s.apiKey=e.target.value;toast('کلید فقط برای همین نشست ذخیره شد');};}
  bind(); render(); if(state.firstRun)openModal('welcomeModal');
})();
